apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://helm.traefik.io/traefik'
    chart: whoami
    targetRevision: HEAD
    helm:
      values: |
        service:
          type: LoadBalancer
          port: 8080
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cool-software-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
